version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lsm123
      POSTGRES_DB: lms
    ports:
      - "4000:5432"   # ðŸ‘ˆ HOST:CONTAINER
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: